# Build website and save it on gh-pages branch
name: build-and-save-website

# Only run this when the master branch is ch
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: gh-pages-deployment
  cancel-in-progress: false

# This job installs dependencies, builds the website and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the site
        env:
          DOCS_VERSION: "v0.0.0"
        run: |
          sphinx-build -nW --keep-going -b html .  _build

      - name: Add .nojekyll file
        run: touch _build/.nojekyll

      # If we've pushed to main, push the book's HTML to github-pages latest directory
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Fetch latest gh-pages
        run: |
          git fetch origin gh-pages 2>/dev/null || true

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Save to gh-pages (latest)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
          destination_dir: latest
          keep_files: true
          force_orphan: false
          # cname: website.com
